project:
  type: book
  output-dir: docs

book:
  title: "Análisis de regresión con R"
  author: "Freddy Hernández"
  date: "9/1/2026"
  chapters:
    - index.qmd
    - 01-rls.qmd
    - 02-transf.qmd
    - 03-rlm.qmd
    - 04-predict.qmd
    - 05-simul.qmd
    - 06-ic.qmd
    - 07-var_cuali.qmd
    - 08-ph1.qmd
    - 09-ph2.qmd
    - references.qmd

bibliography: mis_ref.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

